services:
  servidor-mysql:
    hostname: servidor-mysql
    container_name: servidor-mysql
    image: mysql:latest
    volumes:
      - ./bd/deploy/mysql/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - TZ=America/Sao_Paulo

  back-end:
    hostname: back-end
    container_name: back-end
    build: ./back-end
    ports:
      - "5002:5002"
    depends_on:
      - servidor-mysql
    restart: always
    environment:
      - DB_HOST=servidor-mysql
      - DB_USER=root
      - DB_PASSWORD=1234
      - DB_NAME=teste
      - DB_PORT=3306

#   front-end:
#     hostname: servidor-front-end
#     container_name: servidor-front-end
#     build: ./front-end
#     volumes:
#       - front-volume:/var/www/html
#     restart: always

#   nginx:
#     hostname: servidor-nginx-end
#     container_name: servidor-nginx-end
#     build: ./nginx
#     ports:
#       - 8888:80
#     volumes:
#       - front-volume:/var/www/html
#     depends_on:
#       - servidor-mysql
#       - back-end
#       - front-end
#     restart: always

# volumes:
#   front-volume: