services:
  servidor-mysql:
    hostname: servidor-mysql
    container_name: servidor-mysql
    build: ./bd
    ports:
      - "3306:3306"
    restart: always

  back-end:
    hostname: back-end
    container_name: back-end
    build: ./back-end
    ports:
      - "5002:5002"
    depends_on:
      - servidor-mysql
    restart: always
    environment:
      - DB_HOST=servidor-mysql
      - DB_USER=root
      - DB_PASSWORD=1234
      - DB_NAME=teste
      - DB_PORT=3306

  front-end:
    hostname: servidor-front-end
    container_name: servidor-front-end
    build: ./front-end
    volumes:
      - front-volume:/var/www/html
    restart: always
    environment:
      - REACT_APP_API_URL=http://localhost:5002

  nginx:
    hostname: servidor-nginx
    container_name: servidor-nginx
    build: ./nginx
    ports:
      - 8888:80
    volumes:
      - front-volume:/var/www/html
    depends_on:
      - back-end
      - front-end
    restart: always

volumes:
  front-volume:
